version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
      interval: "daily"
    directory: devops-toolbox
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
