config:
    sensitive:
        KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:llqLKYBclDZA5qlOUpjplw==,iv:9iehKQW7btNbjWgZI3J5zTN3JCp/+IQEkmAtRmzJM34=,tag:pzvHr3JvgP6CfFQy5qrUpg==,type:str]
        KEYCLOAK_FRONTEND_CLIENT_ID: ENC[AES256_GCM,data:Cqr06BHEOVtLZApXkIjTyq0=,iv:h0l7yXSe93jBQJVPkaRLoQVcs+ffzlw6r79NXg/i9wk=,tag:qOgFmLqj0Se+BFw14aFclA==,type:str]
        KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:tgKYtGOp20iI1yHbQ6hpwJ2ot6syjxq6sDe/eUJqryE=,iv:6BmL/zeMyZf6NneFfCKhGG+q5Bt++C//6VuBdejrImw=,tag:dL+oeyIuBu7Xta6jIVwKRg==,type:str]
        E2E_PLAYWRIGHT_USER_PASSWORD: ENC[AES256_GCM,data:4SGQkUP3khgNo7Xz,iv:mc4vfCsinzvjZcy0XwDp1OCItkjuYLfdVbSsEUQ8Oco=,tag:IygqxqdBt5xvzcuAeQVv+w==,type:str]
        E2E_PLAYWRIGHT_ADMIN_PASSWORD: ENC[AES256_GCM,data:qi6+D7ISc+uP10kE,iv:xYs7iK+6X2sryrIhnYrxOBZoCSnctNyJvmLOXm/QSt4=,tag:EgUAWRcJPoBYVokbDSLprw==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeTk3WDRacVFLUGpoeTUv
            bGFwcVpLM3U0S0F0MWUwWENUelZlcWk4RGxrCng3WjFSZWVwNFFZL09MVTFCcFdl
            RTlwRFZuN3A5Z2FDdmRVL0o1aXVCY3cKLS0tIHNyTEdxL2VETk9JVnJTVTJERjNK
            NGJZOEE3RDV1amMvQ0NTL1hKR3ltYzAKAne7TFg8KVq1IyLDNV+ZaJbPvog5rJ9R
            b8imhB6URAGP1N17F5DFwdf6R74c1pp3RR5B1tOk73rifUcSncPZOg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYzBjTjZ3b3ZDYkN0U0NS
            aTBaRkdHaWlNeVNUbXhKdzExWWRBQkRSUFhVCi9DZ3IvVkhteXJoUUJIY1ZFbXlJ
            aUxjTERTMlN4MmRzeFdPVC9SUmI5RDgKLS0tIG5JNCtRa3VlcGRWMUErODE3SWJt
            QTduN3VNVXRNU0hGZkZYSkc3QldFMGcKH8JVYQe1105gymo+pslLmfuiAtmo72RX
            PuU2q+UdD4fmYcU2HkbLb1D8BhvUOrT6e1unc+eed1FSeQ7NlOKghg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOEE0NUlIemFleC9YUnk4
            UkszcHpLODNaNEdaRmVqcWQzSmJuQUxZWGdnCk01TUI2RmpxR1QrUWMrTnFBdFQz
            MVc5LzFPTlRObk54V1ZYbHkrUXhQRmMKLS0tIFBrT3ZKNVcvVW9pblJCTHFYNHR1
            aWljSjdKQ2hidTJjT1ptRGM3T0RhWHMKzi8b3Zg42rQhpuPFdkFII2c39+/v+ck2
            DDx0FDBektGgV8bAOaS5zUsA5TU/4KMujTkEBzEGbamuarqXMffI8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENVd5bGg1TlQxY2tGQ2gx
            WkVieW9QOUloN3IxZGZkUnNaWXVKZC9VYnhnClhJamI3R2ZtMDlDeUordVFuRHNN
            K0g1RG5UUllNbXJaeEhyOU55ckNuRVEKLS0tIFBORW9TeXZ0MDZXY3ZwYXJOWUJ6
            eFhHSUZUSlhFQVR4T0tBelh4U1pudVEKi5rkMiS7v6nIQ/9uZ53VNElnwCmlaN5S
            ub89fvSHMS1aRG4Q+sgLTCUFv7ycdgvrRJvKtVPQfgvxv9Q7DxLAgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNjZoMFkycjhPQk5aK2hm
            ZkFWZjltdEtNeWNUQTR3NldDMEFRL0tHRjFNCmM1R0NueGVSaG93Zk1XYkNzMlls
            K1phNWJpdWNNRVlDUXRGUEgzdjZrSUUKLS0tIGs2UmkxaW5HMVhoeWowNzdKSWJK
            MzQydEo1Vi9udkFtVk1Zc0lzN3BYQ1kKyFWRuLsdwt2Qv1VrYG7KYKigPDuHilFk
            V/4w6I8Zu5UKYdYiyuXVKkvWWBAP3l+T3dCVrDD1T1vsqotI9QhqYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMmUzeWNNTGRmRng2UW9F
            YUtOd2xKa0RwSlRaUkIxaEYva3B6T1orN3o4Cjk5cERaWFBTWCtma01SMm5LYTRF
            Y0t5SzFacHdtMnBtVWVIYVdrRmh4M1kKLS0tIExwMW9TUlhBcWJSbWFWdUozU3Bn
            cTJtcjFmdjVpL25pS0hxMC83N29wUzgKdtKolLg6WD1/LHfAizRhbbtYmQ6oKSv+
            st/c7cCJxCn9VjnLqoV+E4DBkPr77TYKdInHWX8nzA/HxHh0anGwcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T13:56:23Z"
    mac: ENC[AES256_GCM,data:XeJTKz4Z1dpPuy2wa9nhqn9H0BWg3L7Fz8miSuFP8+lBmlz423DWG9goVclMKJNcPTCFmt7VPWfp9U+0oBlCN5IEEILu9BJMtTptJT75QPXd2FlMw7fPM2ph+zcoLBa7NkM6OqUjgmxNp7kULbs+RL4IcJs4evrao/Gr2Ab35H4=,iv:L9GFQJySMEFYUwP9EgfjcPmcR4sphRqVgh7euZp3lBM=,tag:CqcD2KrEEY5M4Q2wsfCG6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
