config:
    sensitive:
        KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:llqLKYBclDZA5qlOUpjplw==,iv:9iehKQW7btNbjWgZI3J5zTN3JCp/+IQEkmAtRmzJM34=,tag:pzvHr3JvgP6CfFQy5qrUpg==,type:str]
        KEYCLOAK_FRONTEND_CLIENT_ID: ENC[AES256_GCM,data:Cqr06BHEOVtLZApXkIjTyq0=,iv:h0l7yXSe93jBQJVPkaRLoQVcs+ffzlw6r79NXg/i9wk=,tag:qOgFmLqj0Se+BFw14aFclA==,type:str]
        KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:tgKYtGOp20iI1yHbQ6hpwJ2ot6syjxq6sDe/eUJqryE=,iv:6BmL/zeMyZf6NneFfCKhGG+q5Bt++C//6VuBdejrImw=,tag:dL+oeyIuBu7Xta6jIVwKRg==,type:str]
        E2E_PLAYWRIGHT_USER_PASSWORD: ENC[AES256_GCM,data:4SGQkUP3khgNo7Xz,iv:mc4vfCsinzvjZcy0XwDp1OCItkjuYLfdVbSsEUQ8Oco=,tag:IygqxqdBt5xvzcuAeQVv+w==,type:str]
        E2E_PLAYWRIGHT_ADMIN_PASSWORD: ENC[AES256_GCM,data:qi6+D7ISc+uP10kE,iv:xYs7iK+6X2sryrIhnYrxOBZoCSnctNyJvmLOXm/QSt4=,tag:EgUAWRcJPoBYVokbDSLprw==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMFRYSEhWVEY4S2pLMUEr
            cy81WElWK0tvZnFSVWwvRmhvakY2QlgrRFQ0CmFPL0xoRkFMWG4rK1FJK2ZBa1lu
            S0xESnFCM0EyOUV4RTlaWVJENm1vMVEKLS0tIC9uTjBCd0UzODI1SGNQRmRPVU5t
            bTExY2JJaTJ4dEhrQUcxNFVpZ2hxbWMKSaeIwzRWsZp1NJhfJ/ouwlTDCTlUc7o8
            +C3S6HdeOM+z/A8kVOSDFYcK+Upnv+HxPylERvJg7HQI3Cx502nOeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTDQ0N3JPMmk4eE45ZW1M
            ZStvbGc2Y0t3TzlFWm9JdUxDeTZCNnRPZDJJCjBONkZlSXlTQWQrNWQyN1ZpQ2ZQ
            TU5NOS93OWdHZHQrWXdVTFJmaWZjYXMKLS0tIHdxTTgxak5MRWZ5U211TzVkWnVW
            cm4ydmJlOW5zckhBYXZ0WEFmZkU0VVUKIkj5DtwkVF+oS3Fnvcr1ZsGLsq3dI892
            Da5257prERtp5wgBFSkjhkw7Hg8ScqlDtwIa+vkGkOH7XY07ubDm/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UWszaE4rT3JheGZUYkxm
            STBnRTVEMmplMlFzVnp2YS8wMzZNY2dEbTFjCjRKQ0tOV1p1c28vdlFZRXNBRFo1
            WmVCMVMwTW44emZGL2VxbUJUYjNvY00KLS0tIG1ncEc0MVQ4QjVDU3gzTmlPS3ZK
            Vjkvd1VzNjZhSlZUZDN5OTVoUUNlTkkKsva2MTQYy8lxkxOndDsXDVd+QDWtci30
            4uTQBWVEM3WSRoIEAfnEQtY6T9nDzwtC00HIZnhJ5nejStBhBrX8dQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaTVjMFowZVNqY0JpK3Z5
            aFBDU3lKYVBLbGYvRFBWNmR6bmZ3c0EwVzA0CmNUTzZrbkh5Vk1pcmRxMFBVOS90
            NG1SdGdjTDRKSlYrRTZkdTlnY2QxNjgKLS0tIG5uQStSWVRKVDZGeGVPbUZzRGhs
            bDdpendOeTRDWU0xN1c2aDBsNTdUc1EKhA9kOQrsmEulyScKLHUJaUE3roFrtdUZ
            LOa5HBIbepkfbqz3tjBs5ffwBVNLaDkNPpl8x5EmJcdJMSKbeO+4ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeXdUaGY3dDhxRUk3Q20w
            dEtrcWZwQ0NtOFFQN25Lb3lCZEhjZUJSNDA4ClR3Z2N6bUIvSk1MQ3NlTEJIU0sv
            UWlBcW4zZEE2azFTYnFlK01UdGx5RVUKLS0tICtXK2xEK043MktscExTbU1PeVA4
            RTkrTWErMlV1ekd4VXRXN1RYeHhNU00KSHez0H9LuiybLcTAc8QQM7GDT9wM3XZe
            osAjRNJtnmayZMCtK7NCHhcsOq3BU/Pcz+RgD2oNSx65bUGJSKF27A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQmVuQXVTa1VSaFcyMDFx
            VjNDTVMvL2hmYVk1ei9ZL2NickI2bWRpbTNFCnFXVUlCZ0ZGRXBYRS96VmR4ZG5J
            Yit6LzE4b2pYMTk5Y2VETEwvcURmTHcKLS0tICtjSC9NbHZjR2Rodkl5dFVGQnpa
            WXNIY042a1M1VHNYbHBMY1BESUlJWGcKhp2oORvza16+jwBl98o2yB1O3Ru3g38O
            pPsVTlGXcAMyViBjI/Al0rUrdgT4srQDUtza2bXjiz4/cn99vWmAsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T13:56:23Z"
    mac: ENC[AES256_GCM,data:XeJTKz4Z1dpPuy2wa9nhqn9H0BWg3L7Fz8miSuFP8+lBmlz423DWG9goVclMKJNcPTCFmt7VPWfp9U+0oBlCN5IEEILu9BJMtTptJT75QPXd2FlMw7fPM2ph+zcoLBa7NkM6OqUjgmxNp7kULbs+RL4IcJs4evrao/Gr2Ab35H4=,iv:L9GFQJySMEFYUwP9EgfjcPmcR4sphRqVgh7euZp3lBM=,tag:CqcD2KrEEY5M4Q2wsfCG6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
