config:
    sensitive:
        EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:BJ2YLKmaChjfGGdfh0G/yit+EX378wEop3GrRWzxZz4vRG3SHcvBT3BvEAKWiaqImls=,iv:XY+kfwDj284dZdCMvZtNpfKmiV7zLTGKDV6uG4V++q4=,tag:KPL6482maOITJh2TY/TM8Q==,type:str]
        KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:XtSYUcwaZ1bV2pj9cYKbiGxUZ1Tr9lrch0fT0p+bE3I=,iv:pfiwJqPJ10Sjyq8wHhGzHPviTy+Xwm3KR3ZYIJh3KYY=,tag:/9vSlcbsQDSp5R1g/CzMZA==,type:str]
        KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:oUbTEEjcKO/UrVRYoeVlFGkD7jo=,iv:/faxpfdzMqCp0f67sztztAO3zi1eilktTcFL6KZhfno=,tag:l/nSJEq4DCmy1ysGlDIDzw==,type:str]
        KEYCLOAK_FRONTEND_CLIENT_ID: ENC[AES256_GCM,data:/kur+PMnIVWW/Z4PxK/H0HQkRwUm,iv:te0SOATSc6HxFXEvMpKkw1T7VwPO0YogPKMCkjNSWsA=,tag:LhOrjTWrGICEg1MvfYVJaQ==,type:str]
        SECRET_KEY: ENC[AES256_GCM,data:sJwexMAZVCkecBisesZJClhmS4GaXdk3P/2D4fuKKEVynr995p7Zh3+sx8+fUD3pMFsAy0l72I0J3rySuUgmcg==,iv:VSfa5QaRmGEOo5BrjaemCLWmUxicxHMcqzal/YEBDWU=,tag:alYASivvIi80uVE4WcIJOg==,type:str]
        AZURE_ACCOUNT_KEY: ENC[AES256_GCM,data:KVp+3Lr60Sh0d9Vym0rHfs+kFRogPn64ZBwTyxV+jfyJzLO959H9tmNDRnFi3MWIYiWJ2OY46UK2wUvofdqO6B2pdmGcZqSZ6t/Q5xA9mjI/qxsUifnZrw==,iv:F4bjalwPwiuN+MnuQu60n/BAiM+pcD6UOgCpUpjcAC4=,tag:XIteBGQDcaq4ka+Y7PGz9w==,type:str]
        AZURE_TRANSLATOR_KEY: ENC[AES256_GCM,data:fpAo0/VmkI/Uk4huvwHWGu/QwZ8YWAX3aNvE7J2r5JTyGPhrFGL/eDgmljnn39MNnz0rpEvQKqbM4MfD63kL0ab4xmP+dqDl0A01Nea2QTRjs9ie,iv:hHiMGbRt2Q3MVbkahkPVxhsITc/mkJjgDMp69DdNa0w=,tag:e0GIpKou5cCLpyjCOFpf7g==,type:str]
        POSTGRES_USER: ENC[AES256_GCM,data:kDxMQ5ZsI2Q=,iv:2AVUqiEyx8iOqQf2EGG7+USii/ilkpHSLkGeWBO5Fns=,tag:swXIbUigtZsRJT1iBuh8Qg==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:Rc5IUcwmfF/nradVeZE=,iv:fBj7OIsbHRnNKfDSPWXc5yqWsxUruQcBnQePA5eSaL8=,tag:gpTTij3aj0vOyST2Xb6h7g==,type:str]
        RECAPTCHA_SECRET_KEY: ENC[AES256_GCM,data:0i30Fnt+AvT2bJKhIeXHTJahlKop5Yb/P8nyKOIDZn1bjxYU1GMw0w==,iv:XyLF0QMnbLvQrwCCChnz2YvDhx0lZERqlAtOlOX4I0k=,tag:jfNJLbxP/U5xIbOwc6wuwA==,type:str]
        MIXPANEL_API_SECRET: ENC[AES256_GCM,data:kg9v6HpztdPjiCaSEhC0O/s2iQ1xjyC2KBmaThfDkRY=,iv:8T0gTMO1kaSgtXgA05TCJUhziHRHfXkL2qpkTTP1Hcg=,tag:WNg51YxlwhY6qPu70vm7Iw==,type:str]
        MISTRAL_API_KEY: ENC[AES256_GCM,data:p6rnJ5sxoB5c5MCl9TF2osq5t5zD/nbNjSdhc9iS9OM=,iv:lFwjf5OtVtIREZYUIjeh/JiwcNO+xybnrnQz2xRV+ew=,tag:0lhD9imDdl+C3msjs8QRpw==,type:str]
        GOOGLE_PRIVATE_KEY_ID: ENC[AES256_GCM,data:y2DjSqBOZBPhla5wlb5NY6D11qnQZTDp7l5mz2kyi7Sns51Ycr0+tw==,iv:Eqeq6/Ve+4HigcdL06tNutBMMPlsICwaN+yyftArjSA=,tag:7BxGt9rt6tQmRkZQw4lJ5w==,type:str]
        GOOGLE_PRIVATE_KEY: ENC[AES256_GCM,data:NnZ8vhLIBNqp2oKp28UNlXiunijgg+stCzNFFKBcyZ169svpp4Mgss9cM8UpHYpmFVVKKPIC91/Ea25mwb3mPIMSwX4SNA05wesD4hkQgftY3BJ+VQ4kdBOWnreL4LGeL255cVwCEu21BjOZnC+a9MTkWczBJ0m0rMh062jeJ7ypxS4hsNY2+aRc1ExDutfsJ3iGp8USV6nowlr0BEJp7p6XmZ3Ma8jW8JFBcPUTzkX6V1UHecz9jGPy5g4zGCLKnLMBB3dxop2M61oiTn3aLpae1jqmB/QCWTHh9/Iq+nb/nJIvZVNH4BZ2BfbYWkArLFvut43cTTq9Ikv81BXTS99K/exCVwnHjz2jt7USunFzVZBO+OwavmH+oEzhaQHS78MHXL1JixBj0uhv0zKzkCXb2bEi8jadyVOW++2SKzAHWppTpOgpcxBva/WSWLBJ4EMZVw02k7SkgzADOEj30GEIPgteMQNbCiUmFq/CKZJDf8byBHKvtkRlGjHyXML89ZV2ickI1BxDZiXmvTLyVTRVtF8N4ONdhGvVgyLm2PKexRuQyY+DJZ9PaCEGNG6Jf/JovciplwEwaKDKtOnRJzWzuuny6pDNzlTZ2EuM/Rkh7DUbU0hGep1DqTuMwWd9WzKbo5c8pTFUg/A2L49kUSrEuGq69SVn8AyOP4QPahVojq6z/r3ClJIPrk02dm8dm1VwT7yNf8RrWraJPm7j5n/D8uey35Jd1OuFuRIiAT7tLUQWJwvGaykCD7F2TMp6QW+slRb5gVMG2veHOTEcyHHQhr1FC9Bh+zzPzRGWeFdvwmbtgwPz2r8cZ8I1DtOeUGgJ40uPiVJtJc983za/0+vemBkisIORbTrAj2h6icUzF/u17Gwvbbsf4cdJarHkKGscBnH3LAR3wJ3EtUc58xxUVGOgtsF7+U9lMo0anHkD2ZgffOmIg5ko79GA2D5jAFqLlkwwRPsamqBjkMYvUF3Vt3JG3BhWcqzwL3WjYpBjLfkp6L5uQ904eYTmx9dcyEauNlvSTRDyy49S24PyRNlDhn6eyujCbk+WjZMUetY5BJUcCBgjNwfBovbZM8+WHaMkVzV0e5rVKKNgoyoI/HFILzbRf2hGi23jvOGnEdb+ieHW8x6CzGCOppw6dOGoSKgVeygz2aDlnF4m8qgFJZBT9II6tO3nuLj9URvIgIzfoZuIEteQs7AvqbXcJDIjNwOeVLIEGg012b4sLXpnryoNDAhwluPuTqq4cIuvmVJvzuU9hyrXqYSCSZebK0heRCcnz/OXGSEg9VlwHgwoDaxfXiXe9IXiTSrQuAt6AjBehnQzVCzvjhbae6U6hVVE0J7A4tSCMU9Bn339QZYjHEgGLK9TBv8N5zBsi7y8j4qF4m1G6RhRcJ/q4WCi26xxRXi7gcn2UI/PP7g9M7waaNE4/SmNooznnmOAfiLM1ZJtR+AbpSo4ZDWWTEE9SEaIZtIbpMfTKgKks48YMnmUjWrSMFvUanq+XwGs1VMBxDgfML0YYcQ0TF7oasqsWHiN0sYc8me8pVtGe+Drqe1KmCCrzS6deAFPfqmdMB+3LFidoo8vErQjWAkmataFgt11Qy85nwz+PBuC1td3h6NcQvdhhdnRDm8haOHMTSQf1z1MW9Vo/n72CT/O2E5DsS0/HlwRQOThuKgD2oFyp6A5Z4eVimqcnzMLATzoTRg4hy7JRdrf2T13tkLVoUGIE/vJDceGiQl5rcEJp7mId1GLnF+6f96G/W3b7kaDEhNTTo7WNJ7Zywr2ayTqroH0POH7Ry3l5X77C795DNAHgou7IulL4d+y7wi1QrF/d4oGFx7k4YqQVB5x37Hu1z+Lc6iqRpgWOw4fVcePmaNgFkkJvbCh029OHRHE9xQNQ2+h0fzTNgmEP6WsRzFy+JVLDdg/KU+CgQFd4I2KwLMIt25KLXjgh91KIpIhRpc5tJ09Os15h7MfKFgawqJo9aAKGUSwx+4iPetlJgEAcoFdDkcuAvvpNZrMwUtZamYFIk8bfgZt/ZDEK2um6GyPSdDPuyhOciqRUCFphTInwNZa3UoSFDAmO3KJucFzscYhu52j2oYzEG4hjL+93kYXs0L5xfXhfSw1v5InFyjmKDpZCKn+sQX6OePuc5lbr8t/8+5vPs6VAHg0vKoGO4OJ/pgTDz2Ngxl7wg73rDnCAmqguUjuHoyxlk/lDEDveyAZAweWU8CI2id8ZBlhRj/PYulnY1DzX13rFjMCSgC32dmu2jnq/0rqqm82OeI7,iv:AZC7Ex4Mt7Gdl/bEczMYt1pokpE2sadmxM2F9msKBU8=,tag:A0iB8z4QeWFsZeHT0H4TLw==,type:str]
        #ENC[AES256_GCM,data:m7VU2A+hI6dN/Fg918y364+VtCE2dQsXES6n0CBygmuGcl5zJW4nxtfKYV2uZ5D4,iv:qydEVmc9nlZtWsUyTjknDD36hWqtjHqbGd1pFwVRRac=,tag:qmI4wET6HqtlOWXUenonvw==,type:comment]
        OPENSEARCH_PASSWORD: ENC[AES256_GCM,data:+P9ifKgoWa3Cyjx2+SGIJ4sDGnQW44ZBEiRJ6/0R2hbuakh8,iv:2BsL6TBATiJ8SBGBKgL1Fjffc8q/BbqwfeNe/a6zZ4U=,tag:U4lzOU51c42FR0SrU5H7Ww==,type:str]
        CRISALID_API_TOKEN: ENC[AES256_GCM,data:P2A/9UNeYY2xLXP//zbow1RLYYOCxPCyP/EsvPaP6zk=,iv:FK4//JDQTrbsqeh8GsMe41I2tM+7radQSTbSKK3TDGo=,tag:uFf3PaNBGW/MtaxlFuEhjQ==,type:str]
opensearchPasswords:
    main: ENC[AES256_GCM,data:/4IA6McTZXXX8zO/2IQ54Ac7b2I=,iv:oTQbdsltebC2ynFjkq4tbHpn00c8sjwssoaqvMh5caA=,tag:C+3BiCAdSO2WjJI898S14A==,type:str]
    ref: ENC[AES256_GCM,data:cIuopesjbKYCp+CJr872mOwB,iv:avmc+3pNKnGNKtnekEaJqq9rQ5uTsL0dg10G7vU6+KU=,tag:B+HLi+xBtTKr27pXYZsT8g==,type:str]
    e2e: ENC[AES256_GCM,data:VxYaOnUoSjRcsQQlcPZh82kS6LA=,iv:APU/SijekzZT7FpwYYtwvJTUhsp39giSn1Vbu3ijyAM=,tag:UbCwg8aK0VKCEuGytyqebg==,type:str]
workflow:
    lifecycle:
        config:
            sensitive:
                ADMIN_POSTGRES_PASSWORD: ENC[AES256_GCM,data:zAPX90dFqHrRLgtNHtvgx66Kmj1MtGB/cqoxAarQ8TgSyXr74TvJCtIs+Au47XxjvF4qnTWEnVH2trUMPV1V9g==,iv:kQESD5zTlVxnHzql+g8pHhBXMvRsUIqSCExq4dSVYAU=,tag:eB4Ag2j02BwXz2nVh/BjYA==,type:str]
                ADMIN_POSTGRES_USER: ENC[AES256_GCM,data:a2HVzQ0OuelZ,iv:482d2Qm0RJ+z1bNpWmJnlNtzIFeZG2iMp67yyt2t41Y=,tag:x2pYksQsyZA+uSMD1AKJfQ==,type:str]
                AZURE_TENANT_ID: ENC[AES256_GCM,data:B4KiKXTV7IayNJlwwK55j+gwV/ln6NmHaWzxKEabEFMtGfDE,iv:q/jLaXl0EGPgDHhBsmDXk6ZlqhD//rq1qucpUQp5OTg=,tag:DQaOI13MDvjyrP/74H+tjA==,type:str]
                AZURE_CLIENT_ID: ENC[AES256_GCM,data:HWs1NumdOo6C8Ig/JkK3LMmRApRYvYKrFm3QiwYCQCaBfKRI,iv:3xWzhn6ojH1qw3L1dtNer1EFl3Q8LVLOIl4mE+hbZE4=,tag:C6OHTTtp3P80tPx9xUqTVA==,type:str]
                AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:4eb7VUpaNG8b5zM3sjkuzTc5mdUOqumdEdkUupnoNJaQKN4Placucw==,iv:qIiVcYwdYYysbmdAP68mRHbeRmORXoLzEoeVAgsKARw=,tag:EkJBcBa6jQsFTlsQ2Kq9RQ==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOUJQWnZUN0c5djRWOEZs
            YytBUWx0cnZ3QitnZHM3Vnpnc2xaQjcwRW5nCnVjdUU0b2tJaHhFSUd1WkpyeVdD
            MlVlOXVmQkp6MERqRlFMZndWdWZlMWcKLS0tIHp1MXB1WUo0MGF5QUQwTWdPTFV4
            NDZsNlIyaDNUQmt4U3YxNGFyMTZJbDgKsLRL1SxcBvDO6UPsr2SKSZB9bdVO9D7K
            xZkwUwD2LBIh3uez5OusXM5EMDpQRDgKI0N4LEqxqtZojTiq8jqn+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL3RJU2grb2RpdkVNaXJy
            VWdTZEpQMXEybVAxYU5mMEd5UnhRaHlWUGxNCkhLQWZFMGdwMVZLek5EVXVXVHdG
            U2RJamlzYjRXM2dyUWhOWFVtR3M5V1EKLS0tIDhzNHluQTFpVVRvWXNta001dlJl
            Zk1wU2NubnIzN04xM0dIdloxTENRak0K21G7JvO60LgDMi8gCRbYvdQNNe2Wjc4q
            LGTDeADj2r45WPj1xfX8vlI3vSM0hOpEmA7RoDA0WkwaoIQaoHwSDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVXk5cGU0SmNIMktMOUpC
            YzNIRHBIYk1KS1VvRHdubDg0ajMydkFXVXdZCi9aeWg1a3h3b0pyTWhIeUJ4K04z
            blpyYS8zWlhnM0JaSC9ZVWlWU3dlUzgKLS0tIFRHVk5lQXp6TUZxcisrK1BhdUdO
            eEFQVCtXZitlaERPQUJETVE5bmsvSFkKSaTcqD/15PGeaNehXw/Z1D6x/eRNy1nk
            ChUe9lKJ9DoxRL93Cbb1Tx0rHds2Z97zEN876fjpjQYF8EXyI2zSxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwczFGR0VOYTBVTURra3U3
            RU1xWm81czFENVVLYTlPbGhURWRJYnZWVUdVClJVcXhTMWQ2WGtwTnFJNUpOMEEr
            Vzdqdm9GVXBCY2VHbEpXSkxNdXJzd00KLS0tIGMrOTVVbjVHNzJ3enNmMERYdjZx
            eHRYb01mQ29TWVZxQ1RsV2t1aWpoQ1kKYv5W2OhqWOMjwD0TY1sxX9Z1EmyECP3v
            h7qWX0tcqmIg8DS5G9+5wMf0MHTlvG/QgcGk17NV+m0krUz+vn9NCw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpR2hERnJHV2kwTFJMaHBI
            bW1KQU43UzJMZTByNkNHOTBtUXB1azMrZWtJCmFiZktqQllaRTlsNkY2cWFHcGY3
            K0t4SVBkS0ZpUVhDTkx1K3FlTmJMUmsKLS0tIGgyYTkzeWlBbW04ZVBpZStwaUlO
            OWhGbXZianB3YWV2dTh0bDBBT2VVR0EKI76nRjoQawJfdM/oy7vXAk6x7ckh8RGY
            uope/w/TSXuF/xyrLbJ8mTG3AI6q4gBtUpMkuGtfp4ea39RcrFcDaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQnI3OHVNYVREdXB6VkxV
            ZW0yZ2lyZ2orUkx0SDc2WjExempZZUp1QUNNCjkvSG5HcnJ5aUE2SFk2T0RMdlI1
            UGlWbHVGWDViMEExOGNrUyt6c1dheHcKLS0tIEVtQXpiNThRR3BPOFJwRU9YTHV6
            NGh5bHpJRFhXUnJ6Uk9IelltWnN2RXcK92IdZv+IKLH+3QF6fWZPEc8F2AvSZdcq
            Y6kaFKYDngGNd6mn2/Fjoz65EOIockL4X9xgHo/3VvnJa5QwmPM/aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T15:30:04Z"
    mac: ENC[AES256_GCM,data:chfsUQco632ZBg5/x/nUhCVjjaMV/Fg7mrT+DHth1l4Ojtew5mHs8Fm2AEi5pmoNQ4dGORkdJP14V8RfhxiZSg7MSMXR0VPCmYWWndM54pN/6EJwypPsDHGe0AWg8flwJmjtdB7EGqsgP3+1xdxiokpxvEJEWVpYAu/Gy/NfkzQ=,iv:imy9AZzIan/aghaBeuIACwDLWyYmb6Qj/1UjxjBZeCw=,tag:bnLJn6jHsS9J2hqmuRKYeg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
